server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /order {
        proxy_pass http://backend:5000/order;
        proxy_set_header Content-Type application/json;
    }
}
