---
- name: Deploy Restaurant App
  hosts: all
  become: yes

  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Copy project files
      copy:
        src: ../
        dest: /home/ubuntu/restaurant-app/

    - name: Run Docker Compose
      command: docker-compose up -d
      args:
        chdir: /home/ubuntu/restaurant-app/
